name: ci_cd

on: 
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          cache: 'yarn'
      - name: install
        run: yarn install
      - name: test
        env:
          IMAGEKIT_PRIVATE_KEY: ${{ secrets.IMAGEKIT_PRIVATE_KEY }}
          IMAGEKIT_PUBLIC_KEY: ${{ secrets.IMAGEKIT_PUBLIC_KEY }}
          IMAGEKIT_URL_ENDPOINT: ${{ secrets.IMAGEKIT_URL_ENDPOINT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
        run: yarn test
      - name: lint
        run: yarn lint

